### ISSUE TITLE
Bin conflict with gulp & gulp-cli

### ISSUE THREAD

**Issue by heikki** [gulpjs/gulp-cli#7] opened 2015-01-05 10:31 UTC
Npm install fails when having gulp-cli as dependency and gulp as devDependency. This is probably because both of them try to link their own gulp bin.

```sh
∴ slush git:(4.0) npm install
 
> v8flags@1.0.8 install /Users/heikki/Desktop/heikki/slush/node_modules/gulp/node_modules/v8flags
> node fetch.js

 
> v8flags@1.0.8 install /Users/heikki/Desktop/heikki/slush/node_modules/gulp-cli/node_modules/v8flags
> node fetch.js

npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/Users/heikki/.nvm-fish/v0.10.35/bin/npm" "install"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.17
npm ERR! path ../gulp-cli/bin/gulp.js
npm ERR! code EEXIST
npm ERR! errno 47

npm ERR! EEXIST, symlink '../gulp-cli/bin/gulp.js'
File exists: ../gulp-cli/bin/gulp.js
Move it away, and try again. 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/heikki/Desktop/heikki/slush/npm-debug.log
```

**Comment by heikki** [comment] 2015-01-05 10:38
Is gulp-cli meant to be installed globally in the future? I'm wondering if both of them need the bin.

I run into this issue in my slush fork: https://github.com/heikki/slush/tree/4.0

**Comment by phated** [comment] 2015-01-05 10:48
gulp-cli was meant to be installed globally but then aliased in gulp so when it is installed locally, you can easily do `gulp whatever` in npm scripts inside package.json without adding gulp-cli to your devDeps.  This was a problem @tkellen pointed out with grunt's approach to grunt-cli. His comment is https://github.com/gulpjs/gulp/issues/805#issuecomment-66880564

**Comment by tkellen** [comment] 2015-01-05 14:04
Whoops, didn't read this code yet. By making gulp-cli a dependency of gulp it should make gulp available in `node_modules/.bin` when installed locally, but it won't make it available globally--for that you'd have to install gulp-cli. Let me confirm these assumptions later today, it's been a long time since I looked at this.

**Comment by heikki** [comment] 2015-01-05 15:32
I'd be happy to use a workaround for this case. So far I have found only bad ones :smile: 
Anyways, there could be issues if people install both gulp & gulp-cli locally or globally.

**Comment by tkellen** [comment] 2015-01-06 00:13
So, my previous assumptions were incorrect, but, @heikki why are you depending on both `gulp-cli` and `gulp` at the same time? You should never need `gulp-cli` in your dependencies.

**Comment by heikki** [comment] 2015-01-06 01:30
@tkellen I linked the [slush fork](https://github.com/heikki/slush/tree/4.0) above. I'm trying to modify slush to use `gulp-cli` instead of copying the same code there. `gulp` was there just for tests i.e. there's a gulpfile that gets called by slush.

Workaround is fine for me. I just thought to bring this up because I'd imagine ppl can get easily things messed. For example install both globally, then uninstall one and boom there's no bins anymore.

Should this be closed as wontfix or is there alternatives left?

**Comment by phated** [comment] 2015-01-06 18:33
@heikki I'd like a way to solve this but we really only have 2 options:

1. Have as a dep of gulp and have the clashing bins when installed next to each other.  - I want to look into npm further to see if we can avoid failing, like an optional bin or something
2. Make gulp-cli a peerDep of gulp so they both get installed upon `npm install`, this works with --save but the remove doesn't.  On top of that, peerDeps have a lot of weird edge cases.

**Comment by heikki** [comment] 2015-01-06 18:52
3. Remove bin from `gulp-cli` and keep using `gulp` for both local & global installs.

Global install would be bigger but wouldn't it solve this issue? Am I overlooking something?

**Comment by phated** [comment] 2015-01-06 19:21
It's a versioning thing. It will be confusing that gulp 3.whatever globally installed can run gulp 4.whatever but only if it is local. Having a separate (smaller being another benefit) module that is versioned separately makes that distinction easier.

**Comment by heikki** [comment] 2015-01-06 19:47
I agree. I'd still rather have that if it prevents breaking things accidentally. I usually install global modules without specifying version and occationally update all of them to latest and expect that things keep working. Random notes:

* Separating `gulp-cli` would still have benefits
* From user perpective local/global gulp would keep working as usual
* 'Warning: gulp version mismatch:' could be more explicit 'Warning: global gulp is outdated, please run npm update -g gulp' or similar

**Comment by heikki** [comment] 2015-01-06 23:55
That explains.. :smile:  Can't get better (and more logical) cli separation than that.

**Comment by phated** [comment] 2015-01-11 00:14
Looking into this more.

I just attempted `npm install gulpjs/gulp#4.0 gulpjs/gulp-cli#4.0` and it works sometimes.  This seems to be a race condition in the unlinking of the previous `bin` and I will talk with @othiym23 about it.  They don't seem to have a problem when installed separately because of the unlink.  I think the EEXIST is also a bug in npm given the behavior of global.  Will ask about that also.

**Comment by othiym23** [comment] 2015-01-12 20:09
I would believe there's an issue here, and it would be a lot easier for me to get traction on establishing where the issue is if you could do me a solid and reduce the failure to a minimal test case. File an issue in the meantime, so I have something I can track. Thanks!

It's worth pointing out that this will 100% be affected by the changes to the install in `npm@3`, which @iarna is getting close to releasing as a beta. I'm mentioning her so she knows this is an edge case to watch out for.

**Comment by heikki** [comment] 2015-01-13 16:58
@othiym23 Is simple package.json ok for test case?

https://gist.github.com/heikki/eae172b8d1c5a97ed5ef#file-package-json

**Comment by othiym23** [comment] 2015-01-13 22:03
@heikki I can't get the attached `package.json` to barf, at least with `npm@2.2.0` on Windows 8.1. If it were failing semi-reliably, yes, that would absolutely be enough for me to work from.

**Comment by heikki** [comment] 2015-01-13 22:17
@othiym23 on osx & `npm@2.1.8` I see fails maybe 50% of the time. I delete node_modules after each try. Not sure if that makes any difference.

**Comment by phated** [comment] 2015-01-14 01:28
@othiym23 was there a change in 2.2 that would cause this to not happen anymore?  Also, the command `npm install -g gulpjs/gulp#4.0 gulpjs/gulp-cli#4.0` can be used to get this to happen for a global install ~50% of the time on OSX.

**Comment by heikki** [comment] 2015-01-14 01:47
I'm seeing this in 2.2 too. Mentioned in npm issue: https://github.com/npm/npm/issues/7130

**Comment by phated** [comment] 2015-01-14 02:03
@heikki thanks for opening the issue, as I am out of town and don't have much time until next week.

**Comment by silkentrance** [comment] 2015-01-15 23:09
Running `npm install` twice seems to do the trick, though.

**Comment by silkentrance** [comment] 2015-01-15 23:11
Perhaps renaming grunt-cli/bin/grunt.js to grunt-cli/bin/grunt will do the trick?

**Comment by phated** [comment] 2015-01-15 23:38
@silkentrance no, this is an npm issue as stated above

**Comment by ibc** [comment] 2015-01-26 19:38
AFAIU the idea behind `gulp-cli` and `gulp` is that `gulp-cli` must be globally installed (so it provides the `gulp` bin) while `gulp` must be locally installed.

AFAIK the same "bin" problem would happen if somebody globally installs both `grunt` and `grunt-cli`.

**Comment by phated** [comment] 2015-01-26 19:40
@ibc grunt opted to not expose a bin from the main grunt module.  @tkellen told us the downsides to that and suggested we ship a bin with both, hence the problem.

**Comment by ibc** [comment] 2015-01-26 19:41
OK, then just properly document that `gulp` should not be globally installed but, instead, that is what `gulp-cli` exists for.

**Comment by phated** [comment] 2015-01-26 19:42
@ibc the people that currently have gulp installed and then install this globally will have problems.  We aren't shipping it until npm fixes their bug because none of us want to field npm bugs in the gulp issue tracker.

**Comment by silkentrance** [comment] 2015-01-26 20:44
@phated while it seems nice to have both packages expose a bin/gulp.js, it might not be the wisest decision and also might oppose all best practices established so far. I would go for the standard way and have both a gulp-cli package that exposes the binary and a second API package that exposes the API.

And since the tool/API is in a rather early stage of development I would simply go for it instead of waiting for the peops over at npm to fix the issue, considering their overall backlog.

**Comment by phated** [comment] 2015-01-26 21:08
We are going to ship both. It is annoying to have to have something like gulp-cli in devDeps just to have access to the bin in your npm scripts

**Comment by sindresorhus** [comment] 2015-01-26 21:10
@phated I disagree. Separation of concerns is a good thing. "one way of doing things" is too.

**Comment by phated** [comment] 2015-01-26 21:12
@sindresorhus I don't care because @tkellen's advice was correct. I hate how grunt does it currently

**Comment by silkentrance** [comment] 2015-01-26 22:34
@phated the way grunt and other tools do it works just fine. @tkellen please advise.

**Comment by phated** [comment] 2015-01-26 22:49
@silkentrance dude, it's already been quoted and linked in this thread.  Locking.

**Comment by phated** [comment] 2015-07-12 21:45
@heikki would you be able to test these use cases again but with npm 3.x?  If npm3 has solved this (or at least gave us a determinate behavior), then I'd be good with shipping the CLI.

**Comment by heikki** [comment] 2015-07-13 12:20
@phated 

I don't see `EEXIST` or `ENOENT` errors anymore with npm 3.1.0.

Linked gulp bin varies:

```sh
∴ npm-install-bin-conflicts git:(master) ./enoent.sh
Running 'npm install gulp gulp-cli' repeatedly
install 1, gulp bin -> ../gulp-cli/bin/gulp.js
install 2, gulp bin -> ../gulp/bin/gulp.js
install 3, gulp bin -> ../gulp/bin/gulp.js
install 4, gulp bin -> ../gulp/bin/gulp.js
install 5, gulp bin -> ../gulp/bin/gulp.js
install 6, gulp bin -> ../gulp/bin/gulp.js
install 7, gulp bin -> ../gulp/bin/gulp.js

∴ npm-install-bin-conflicts git:(master) ./eexist.sh
Running 'rm -fr node_modules && npm install gulp gulp-cli' repeatedly
install 1, gulp bin -> ../gulp-cli/bin/gulp.js
install 2, gulp bin -> ../gulp-cli/bin/gulp.js
install 3, gulp bin -> ../gulp/bin/gulp.js
install 4, gulp bin -> ../gulp-cli/bin/gulp.js
install 5, gulp bin -> ../gulp-cli/bin/gulp.js
install 6, gulp bin -> ../gulp-cli/bin/gulp.js
install 7, gulp bin -> ../gulp-cli/bin/gulp.js
```

`npm uninstall -g gulp` still removes the gulp bin even if it belongs to gulp-cli package:

```
∴ ~ npm list -g
/Users/heikki/.nvm/versions/node/v0.12.7/lib
├── gulp@3.9.0
└── npm@3.1.0

∴ ~ npm install -g gulp-cli
/Users/heikki/.nvm/versions/node/v0.12.7/bin/gulp -> /Users/heikki/.nvm/versions/node/v0.12.7/lib/node_modules/gulp-cli/bin/gulp.js
/Users/heikki/.nvm/versions/node/v0.12.7/lib
└── gulp-cli@0.3.0 

∴ ~ gulp -v
[15:10:14] CLI version 0.3.0

npm uninstall -g gulp

∴ ~ gulp -v
fish: Unknown command 'gulp'
```

**Comment by iarna** [comment] 2015-07-13 19:55
These both look like npm bugs to me– given the same module list it should be linking modules in the same order and apparently it isn't. And given that `gulp-cli` owns the link after the second install, removing `gulp` absolutely shouldn't remove it.

I'll open these as issues over on the npm tracker and link here.

**Comment by phated** [comment] 2015-07-13 20:01
@iarna thank you so much!

**Comment by iarna** [comment] 2015-08-14 00:56
Hey you all, can any of you reproduce the "different install orders" thing with `npm@v3.x-next`? I'm pretty sure that can't happen any more.

**Comment by heikki** [comment] 2015-08-14 01:52
Yes, details here -> https://github.com/npm/npm/issues/8995#issuecomment-130917005

**Comment by contra** [comment] 2015-08-21 20:31
The new npm is out, can we test and verify that this is fixed?

**Comment by phated** [comment] 2015-08-21 20:54
@contra it isn't out yet.  Should be out today, I think

**Comment by phated** [comment] 2015-08-21 20:59
For reference, the version we want to test this against will be 3.3.1 (currently "next" is 3.3.0)

**Comment by iarna** [comment] 2015-08-22 16:51
Yup, 3.3.1 got bumped to next week for process reasons. If you already have 3.x installed somewhere, you can try out 3.3.1 by installing `npm/npm#release-3.3.1` with it.

**Comment by heikki** [comment] 2015-08-22 20:58
Install order looks consistent with `npm/npm#release-3.3.1`.

```sh
Running 'npm install gulp gulp-cli' repeatedly
install 1, gulp bin -> ../gulp-cli/bin/gulp.js
install 2, gulp bin -> ../gulp-cli/bin/gulp.js
install 3, gulp bin -> ../gulp-cli/bin/gulp.js
install 4, gulp bin -> ../gulp-cli/bin/gulp.js
install 5, gulp bin -> ../gulp-cli/bin/gulp.js
install 6, gulp bin -> ../gulp-cli/bin/gulp.js
install 7, gulp bin -> ../gulp-cli/bin/gulp.js
```

**Comment by phated** [comment] 2015-09-09 23:09
:tada: :balloon: :birthday: :fireworks: :beers: Closing this now.

**Closed by phated** 2015-09-09 23:09 UTC
Labels: blocked
