### ISSUE TITLE
add support for a gulpfile.babel.coffee configuration

### ISSUE THREAD

**Issue by jhessin** [gulpjs/gulp-cli#160] opened 2018-04-11 15:31 UTC
I thought I could do this myself and give a pull request - but alas my JavaScript skills aren't up to par.

I know that gulp will automatically compile a gulpfile.coffee and it will transpile a gulpfile.babel.js. However it should support doing both with a gulpfile.babel.coffee. This would be simple to do with gulp, or even just using a package like `coffee-babel` (yea - I made that). Currently that is what I am doing by adding both a gulpfile.js and gulpfile.coffee and having the gulpfile.js do this:

```javascript
require('coffee-babel')({
  transpile: {
    presets: ['env']
  },
})

module.exports = require('./gulpfile.coffee');
```

I could easily avoid the extra dependency by inlining this like so:

```javascript
require('module').prototype.options = {
  transpile: {
    presets: [ 'env' ]
  }
};
require('coffeescript/register');
```

I forked both this repo as well as the gulp repo itself and searched for coffee in both and found nothing outside of .md and tests. Where does it resolve the default gulpfile?

**Comment by phated** [comment] 2018-04-11 15:38
There are *years* old bugs that make this impossible currently. I'll link and close this when I'm at a computer.

**Comment by jhessin** [comment] 2018-04-11 15:41
That is not an answer. When you run `gulp` at a command line it finds one of these:
gulpfile.js
gulpfile.coffee
gulpfile.babel.js

Where does the logic for this come from? I'm willing to do the work I just need some direction.

**Comment by phated** [comment] 2018-04-11 16:59
Duplicate of https://github.com/js-cli/js-rechoir/pull/34 and https://github.com/js-cli/js-rechoir/pull/26 - neither of which solve the issue because `require.extensions` is super weird in node.  I had some stuff I was working on locally but it didn't work out.

**Closed by phated** 2018-04-11 16:59 UTC
