### ISSUE TITLE
Liftoff returning empty env.modulePackage object to gulp. Breaks SemVer version comparison.

### ISSUE THREAD

**Issue by bill-barron** [gulpjs/gulp-cli#33] opened 2015-09-11 20:57 UTC
I just did a new install of gulp with and without the global flag. After that I tried to run a task and got the following error:

    C:\Users\USERNAME\AppData\Roaming\npm\node_modules\gulp\node_modules\semver\semver.js:281
    throw new TypeError('Invalid Version: ' + version);
    ^

    TypeError: Invalid Version: undefined
    at new SemVer (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\gulp\node_modules\semver\semver.js:281:11)
    at SemVer.compare (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\gulp\node_modules\semver\semver.js:350:13)
    at compare (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\gulp\node_modules\semver\semver.js:574:31)
    at Function.gt (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\gulp\node_modules\semver\semver.js:603:10)
    at Liftoff.handleArguments (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:103:14)
    at Liftoff.<anonymous> (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:192:16)

    at module.exports (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)
    at Liftoff.<anonymous> (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:185:9)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:159:9
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\gulp\node_modules\v8flags\index.js:99:14

It turns out in gulp.js inside the handleArguments function, env.modulePackage.version is undefined. It gets this from Liftoff so possibly Liftoff isn't doing its job or gulp is calling it wrong or something with my mchine is messed up.

If I give it a value everything works fine:

    env.modulePackage.version = env.modulePackage.version || '3.9.0';

Node version: 4.0.0
npm version: 2.14.2
gulp-cli version: 3.9.0
gulp local version: 3.9.0

**Comment by phated** [comment] 2015-09-11 21:06
I am pretty sure you don't have a local version of gulp.  See https://github.com/gulpjs/gulp/issues/1088#issuecomment-122157366 for more reference.

**Comment by phated** [comment] 2015-09-14 07:05
Closing, as the only way this happens is when there is no local gulp.  I'd love someone to send a PR that gives a better error message when no local gulp exists.

**Closed by phated** 2015-09-14 07:05 UTC

**Comment by bill-barron** [comment] 2015-09-14 14:20
I appreciate your help, but I just wanted to reiterate that gulp is installed both locally and globally. When I manually add the correct version number in the global gulp.js code everything runs fine.

My project is on a mapped network dive though. So instead of \\server\path\gulpfile.js and \\server\path\node_modules it is mapped to r:\gulpfile.js and r:\node_modules

**Comment by tkellen** [comment] 2015-09-14 14:21
Please see https://github.com/gulpjs/gulp-cli/issues/34 and provide a list of steps to reliably reproduce this problem and I'd be glad to look into it!

**Comment by phated** [comment] 2015-09-14 23:54
@tkellen @bill-barron I think your issue is a duplicate of https://github.com/gulpjs/gulp/issues/1251 because findup-sync uses glob and the 4.x branch has problems with network drives.

**Comment by tkellen** [comment] 2015-09-15 01:49
:+1: that seems likely to me.
