### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by darsain** [gulpjs/gulp-cli#12] opened 2015-01-20 14:24 UTC
I wish I could be more specific in the title, but I have no idea what the issue is in here :)

Setup: windows + `gulp-cli@0.1.5` + `gulp@#4.0`

Error after runing `gulp` inside `d:\websites\project`:

```
[15:12:17] Working directory changed to d:\websites\project
[15:12:18] Using gulpfile d:\websites\project\gulpfile.js
C:\Users\Darsain\AppData\Roaming\npm\node_modules\gulp-cli\index.js:133
    gulpInst.start.apply(gulpInst, toRun);
                  ^
TypeError: Cannot read property 'apply' of undefined
    at C:\Users\Darsain\AppData\Roaming\npm\node_modules\gulp-cli\index.js:133:19
    at process._tickCallback (node.js:372:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:124:16)
    at node.js:842:3
```

**Comment by darsain** [comment] 2015-01-20 14:36
What works as global `gulp` command:

- [ ] gulp@3.8.10 - *error above*
- [ ] gulp-cli@0.1.5 - *error above*
- [x]  gulp@4.0.0-alpha.1 - **works fine**

**Comment by heikki** [comment] 2015-01-20 14:47
Use 4.0 branch of gulp-cli with 4.0 branch of gulp.

**Comment by heikki** [comment] 2015-01-20 14:48
Duplicate of #9

**Comment by darsain** [comment] 2015-01-20 15:03
Oh? I wouldn't even think that exists, as I thought that the whole point of gulp-cli is to work with all gulp versions, so we don't have to juggle global `gulp` installs.

Is there a reason why it doesn't work like that? I thought that gulp-cli would mostly do nothing on it's own, and be merely a proxy to local `node_modules/bin/duo`.

**Comment by heikki** [comment] 2015-01-20 15:17
It is not finished.

**Closed** 2015-01-20 16:01 UTC
