### ISSUE TITLE
gulpInst.start.apply(gulpInst, toRun); TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by kshitijbahul** [gulpjs/gulp-cli#84] opened 2016-06-24 21:30 UTC
I have the following entry in my package.json file 
"gulp": "github:gulpjs/gulp#4.0"

i ran npm install -g "gulpjs/gulp-cli#4.0" and it gives me and error `fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.`

Here is the error I get when I run gulp
**gulp
[02:49:31] Using gulpfile ~/Documents/XXXX/gulpfile.js
/usr/local/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)
    at node.js:449:3**

Also The Output for gulp -v
`gulp -v
[02:55:57] CLI version 3.9.1`
`[02:55:57] Local version 4.0.0-alpha.2`

**Comment by phated** [comment] 2016-06-24 21:32
No idea why you are trying to install a branch that doesn't exist.  Duplicate of https://github.com/gulpjs/gulp-cli/issues/83

**Closed by phated** 2016-06-24 21:32 UTC

**Comment by kshitijbahul** [comment] 2016-06-24 21:35
npm install -g "gulpjs/gulp-cli#4.0" was given as a solution for the issue 
gulpInst.start.apply(gulpInst, toRun);
^

TypeError: Cannot read property 'apply' of undefined

Could you let me know how should I get past this then ?

**Comment by phated** [comment] 2016-06-24 21:37
https://www.npmjs.com/package/gulp-cli

**Comment by kshitijbahul** [comment] 2016-06-24 21:59
I did everything mentioned there 
npm install gulp-cli and even tried adding "gulp-cli": "github:gulpjs/gulp-cli"  to my package.json but i still get the issue 

gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined

**Comment by phated** [comment] 2016-06-24 22:22
Please read the docs: https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md

This is not a support forum.

**Comment by mderoche** [comment] 2016-07-13 01:08
@phated, why the persistent rudeness?  Numerous pages across the web give `npm install -g "gulpjs/gulp-cli#4.0"` as a solution to this problem.  His question is completely valid.

**Comment by postor** [comment] 2016-08-16 02:29
use local gulp-cli can make it run
`node ./node_modules/gulp/bin/gulp.js`

**Comment by ElijahLynn** [comment] 2016-08-29 03:09
Thanks @postor 

I noticed my local gulp-cli version was 1.2.2 and my global version was 3.9.1. I checked NPM repo and latest suggested was 1.2.2, I have no idea how that happened but I did install gulp ages ago. I went ahead and installed gulp again globally and now I am at 1.2.2 and it works without that OP error.

**Comment by jacksky007** [comment] 2016-09-19 07:37
I suffered the same issue in this case: install node and gulp(3.x) first, then remove node and install nvm instead, then install gulp-cli and gulp(4.0). After I removed the old gulp in <code>/usr/local/bin</code>, everything works.

**Comment by anandchristal** [comment] 2016-12-21 05:04
changed "gulp": "node node_modules/gulp/bin/gulp.js" in scripts:->under package.json
and also when run ....npm run gulp picked the local version

**Comment by yairEO** [comment] 2017-01-11 21:37
@anandchristal - please explain better. which `package.json`? gulp's or your own? what exactly did you change **to** what?

**Comment by liratanak** [comment] 2017-01-16 20:47
I ran into the similar issue:
```
/home/me/.nvm/versions/node/v6.9.2/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /home/me/.nvm/versions/node/v6.9.2/lib/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

I tried:
> `npm i -g gulp-cli`

Then error just gone :-)

**Comment by Paqura** [comment] 2017-01-19 12:51
npm i -g gulp-cli 

it's rly working

**Comment by shinusuresh** [comment] 2017-02-04 02:32
`npm i -g gulp-cli` works for me too :+1:

**Comment by eliprodigy** [comment] 2017-02-13 11:16
npm i -g gulp-cli works for me too 👍

**Comment by asebold** [comment] 2017-02-16 15:47
I was also getting this when trying to set up a new foundation site on linux. `npm i -g gulp-cli` fixed it.
