### ISSUE TITLE
Continue flag fails.. many times.

### ISSUE THREAD

**Issue by TrySound** [gulpjs/gulp-cli#60] opened 2016-02-09 23:40 UTC
Here's when I run `dev` task with continue flag
Seems like it just log that error on every dependent task.
```
[02:37:26] Using gulpfile D:\_host\github\case\gulpfile.js
[02:37:26] Starting 'dev'...
[02:37:26] Starting 'watch'...
[02:37:26] Finished 'watch' after 12 ms
[02:37:26] Starting 'server'...
[02:37:26] Started server on http://localhost:8080
[02:37:26] Finished 'server' after 62 ms
[02:37:26] Starting 'build'...
[02:37:26] Starting 'clean (skipped)'...
[02:37:26] Finished 'clean (skipped)' after 3.61 ms
[02:37:26] Starting '<parallel>'...
[02:37:26] Starting 'markup'...
[02:37:26] Starting 'script'...
[02:37:26] Starting 'style'...
[02:37:26] Starting 'image'...
[02:37:27] Finished 'image' after 1.21 s
[02:37:27] Finished 'script' after 1.23 s
[02:37:27] 'markup' errored after 1.23 s
[02:37:27] Error in plugin 'gulp-file-include'
Message:
    ENOENT, no such file or directory 'D:\_host\github\case\app\markup\sss'
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
[02:37:27] Finished 'style' after 1.27 s
[02:37:27] '<parallel>' errored after 1.28 s
[02:37:27] 'build' errored after 1.3 s
[02:37:27] Error: Error in plugin 'gulp-file-include'
Message:
    ENOENT, no such file or directory 'D:\_host\github\case\app\markup\sss'
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
    at formatError (D:\_station\nvm\v0.12.7\node_modules\gulp-cli\lib\versioned\^4.0.0\formatError.js:20:10)
    at Gulp.<anonymous> (D:\_station\nvm\v0.12.7\node_modules\gulp-cli\lib\versioned\^4.0.0\log\events.js:30:15)
    at Gulp.emit (events.js:129:20)
    at Object.error (D:\_host\github\case\node_modules\undertaker\lib\helpers\createExtensions.js:58:10)
    at Object.after (D:\_host\github\case\node_modules\undertaker\lib\helpers\createExtensions.js:43:21)
    at handler (D:\_host\github\case\node_modules\now-and-later\lib\mapSeries.js:47:12)
    at f (D:\_host\github\case\node_modules\once\once.js:17:25)
    at D:\_host\github\case\node_modules\async-settle\index.js:17:5
    at f (D:\_host\github\case\node_modules\once\once.js:17:25)
    at done (D:\_host\github\case\node_modules\async-settle\node_modules\async-done\index.js:26:12)
[02:37:27] 'dev' errored after 1.38 s
[02:37:27] Error: Error in plugin 'gulp-file-include'
Message:
    ENOENT, no such file or directory 'D:\_host\github\case\app\markup\sss'
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
    at formatError (D:\_station\nvm\v0.12.7\node_modules\gulp-cli\lib\versioned\^4.0.0\formatError.js:20:10)
    at Gulp.<anonymous> (D:\_station\nvm\v0.12.7\node_modules\gulp-cli\lib\versioned\^4.0.0\log\events.js:30:15)
    at Gulp.emit (events.js:129:20)
    at Object.error (D:\_host\github\case\node_modules\undertaker\lib\helpers\createExtensions.js:58:10)
    at Object.after (D:\_host\github\case\node_modules\undertaker\lib\helpers\createExtensions.js:43:21)
    at handler (D:\_host\github\case\node_modules\now-and-later\lib\map.js:50:12)
    at f (D:\_host\github\case\node_modules\once\once.js:17:25)
    at D:\_host\github\case\node_modules\async-settle\index.js:17:5
    at f (D:\_host\github\case\node_modules\once\once.js:17:25)
    at done (D:\_host\github\case\node_modules\async-settle\node_modules\async-done\index.js:26:12)
```

**Comment by TrySound** [comment] 2016-02-09 23:41
Also are these details correct?
```
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```

**Comment by TrySound** [comment] 2016-02-09 23:43
Without continue is pretty normal like here
https://github.com/gulpjs/undertaker/issues/59

**Comment by phated** [comment] 2016-02-09 23:54
Domain properties are a duplicate of https://github.com/gulpjs/gulp/issues/1329 - feel free to dig into that issue.

This output looks correct but I'd have to see your gulpfile to fully verify.  Wondering if you are using an old version of gulp-cli because in newer versions, we only log an instance of an error once.

**Comment by TrySound** [comment] 2016-02-09 23:56
```
[02:56:43] CLI version 1.2.0
[02:56:43] Local version 4.0.0-alpha.2
```

**Comment by phated** [comment] 2016-02-09 23:58
Then each task is errorring with a different instance - see https://github.com/gulpjs/gulp-cli/blob/master/lib/versioned/%5E4.0.0/log/events.js#L40 for where we filter out error logging.  Closing this as it doesn't seem like a bug.

**Closed by phated** 2016-02-09 23:58 UTC

**Comment by TrySound** [comment] 2016-02-10 00:05
Here's my gulpfile
https://github.com/TrySound/case/blob/3.0/gulpfile.js
Why you think it's not a bug? `--continue` flag should continue, but build is failed.

**Comment by phated** [comment] 2016-02-10 00:11
Everything completed.  Take a look at the output, you are no longer receiving "Task did not complete" warnings and every parallel task has been completed.  Upon completion, if there was an error, we `process.exit(1)` but we wait until every task is done.

**Comment by TrySound** [comment] 2016-02-10 00:15
@phated Yeah. You are right. Okay, `continue` bubbles errors in dep tree. But.. why the output is different? In first case stack trace is hidden in the dependent tasks not.

**Comment by phated** [comment] 2016-02-10 00:19
The error object is printed the first time it is emitted, then it is added to the list of logged errors and not logged again for the higher order functions (instead they just say "<task> errored")

**Comment by TrySound** [comment] 2016-02-10 00:22
Looks ugly and useless don't u thnk? Maybe somehow filter or log just error message? This will minify ouput a lot.

**Comment by phated** [comment] 2016-02-10 00:24
No, we aren't going to remove stack traces.  They help with debugging.  If you want to help on the domain issue to clean up that clutter, feel free.

**Comment by TrySound** [comment] 2016-02-10 00:32
@phated Those stack traces doesn't make sense at all. All details are in the first log. Next loggin can just show `error is here`, but details will be above. What is the reason to duplicate the same and the same messages?
